version: "3.8"

services:
  app:
    container_name: weather-app-ctn
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 4546:3000
